INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Strombeek-Bever","208-1188 Amet Av.",103);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Cumberland","134-1145 Duis Rd.",154);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Vucklabruck","899-7686 Augue St.",274);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Rijkevorsel","Ap #958-2000 Semper St.",115);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Graz","2866 Justo. Avenue",239);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Jerzu","P.O. Box 676, 2689 Nulla Av.",232);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Wanganui","418-1738 Morbi Ave",178);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Morro d'Alba","292-8653 Aliquam St.",221);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Nocera Umbra","128 Sem. Av.",181);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Borchtlombeek","Ap #148-959 Pede Ave",177);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Tranent","7130 In Rd.",290);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Attigliano","3613 Et Street",285);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Oelegem","P.O. Box 436, 323 Enim, Road",299);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Castelvecchio Calvisio","P.O. Box 304, 8559 Ipsum Avenue",116);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Labrecque","P.O. Box 837, 3773 Consequat St.",246);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Duluth","937-4092 Hymenaeos. Road",242);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Sandy","Ap #341-628 Vitae Rd.",248);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Port Coquitlam","8971 Odio Ave",240);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Saint-L?onard","P.O. Box 132, 9866 Donec Rd.",150);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Nodebais","2790 Ornare, Rd.",278);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Port Alice","Ap #454-5803 Mus. Av.",172);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Lanark","P.O. Box 958, 2815 Mauris Rd.",132);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Xhoris","225-1868 Dui. St.",287);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Stony Plain","Ap #326-7272 Neque. Avenue",124);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Neuville","P.O. Box 711, 8286 Purus, St.",265);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Markkleeberg","P.O. Box 658, 8189 Semper St.",137);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Ettelgem","280-4074 Donec Road",228);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Fort Providence","Ap #815-4940 Id, Rd.",119);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Poggiodomo","P.O. Box 288, 2338 Facilisi. St.",156);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Toronto","4613 Mauris, St.",158);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Scandriglia","685-2054 Semper St.",220);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Loppem","Ap #764-5831 Augue Avenue",123);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Prince Albert","479-8227 Vivamus Rd.",229);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Poviglio","9204 Ut Av.",285);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Evere","P.O. Box 951, 4595 Ultricies Road",152);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Borghetto di Borbera","233 Est, Rd.",272);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Ch?telineau","711-9299 Ipsum Rd.",250);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Palanzano","P.O. Box 998, 6563 Euismod St.",127);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Neusiedl am See","2942 Phasellus St.",288);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Jennersdorf","Ap #737-931 Adipiscing Av.",246);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Paulatuk","P.O. Box 705, 3084 Integer Ave",225);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Aieta","2759 Nec, Rd.",283);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Glauchau","Ap #564-7790 Aliquam Avenue",106);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Gontrode","Ap #761-7656 Arcu. Street",180);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Merthyr Tydfil","P.O. Box 676, 3704 Scelerisque, Rd.",265);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Empoli","173-1151 Semper St.",270);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Iqaluit","7542 Molestie Ave",234);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Sint-Niklaas","858-218 Mauris Rd.",260);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Bressoux","1120 Congue, Rd.",106);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Laramie","Ap #108-3476 Interdum. Ave",229);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Jupille-sur-Meuse","P.O. Box 535, 6039 Dolor Ave",223);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Sinaai-Waas","8826 Orci, Road",227);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Warminster","242-8367 Viverra. Rd.",123);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("North Vancouver","8384 Magna. St.",181);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Drayton Valley","976 Orci, Road",210);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Dallas","4203 Pede. Av.",181);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Yorkton","P.O. Box 757, 4164 Netus Ave",180);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Thiaumont","P.O. Box 751, 8852 Et Ave",294);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Isernia","P.O. Box 558, 1513 Sed Ave",220);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Ranst","377-5063 Nunc Ave",153);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Roubaix","788-4542 At Ave",172);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Baie-d'Urf?","Ap #773-5321 Egestas Ave",267);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Castri di Lecce","5197 Eleifend. Av.",204);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("North Saanich","Ap #953-5750 Magna. Rd.",145);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Itajau","Ap #164-6478 Nulla. Ave",173);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Compiugne","9043 Sem Av.",235);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Akron","P.O. Box 389, 8920 Felis. Road",190);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Traiskirchen","Ap #659-9907 Dis Avenue",161);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Ancaster Town","426-7584 Interdum. Av.",123);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Cinisi","297-1790 Mauris Ave",146);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Fossato di Vico","606-3273 Nisi Avenue",205);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Beauvais","P.O. Box 901, 9443 Eu Avenue",231);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Teralfene","Ap #886-8372 Fringilla, Avenue",112);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Dunoon","476-9436 Imperdiet St.",242);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Overland Park","Ap #269-8383 Odio. Avenue",119);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Blehen","Ap #431-6027 Purus Rd.",229);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Annapolis County","4821 Eleifend Street",151);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Pelago","Ap #628-6844 Rutrum St.",238);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Kerkhove","Ap #764-7504 Nec Rd.",204);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Ethe","717-5181 Vulputate, Road",113);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Poucet","1502 Ultricies Rd.",141);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("San Polo d'Enza","Ap #423-448 Nunc. Ave",221);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Shawville","Ap #549-3926 Augue Street",139);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("San Giovanni Lipioni","Ap #526-8802 Metus Avenue",292);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Runcorn","8888 Dignissim Rd.",171);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Rodgau","1238 Aliquam Rd.",182);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Charleville-Muziures","Ap #312-6425 Libero. Ave",140);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Vancouver","4010 Turpis. Ave",257);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("uvila","Ap #295-3505 Libero Road",185);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Cupar","Ap #252-708 Vulputate Road",205);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Paradise","P.O. Box 516, 2766 Dolor Rd.",269);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Guardia Sanframondi","P.O. Box 124, 6853 Rutrum Rd.",289);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Buckingham","4210 Cursus. Ave",122);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Cherain","4207 Mauris Rd.",154);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Neuville-en-Condroz","648-1134 Enim Road",159);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Quimper","Ap #119-7987 Cursus. Ave",104);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Galashiels","P.O. Box 981, 9850 Fusce St.",152);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Arsimont","4352 Ullamcorper Ave",162);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Trochu","Ap #679-8128 Ridiculus Ave",296);
INSERT INTO Iut (nom_iut,adresse,nb_etu) VALUES ("Meer","701-2679 Elit, St.",113);